# Use an official Python runtime as a parent image
FROM python:3.11-slim

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONPATH /app
ENV PORT 5000

# Set the working directory in the container
WORKDIR /app

# Install system dependencies if any are needed (e.g., for some python packages)
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container
# Since requirements.txt might be UTF-16, we might need a step to ensure it's readable
# but usually pip handles it if it's generated by pip freeze.
# However, to be safe, we'll just copy everything.
COPY requirements.txt .

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Make entrypoint script executable
RUN chmod +x entrypoint.sh

# Expose the port the app runs on
EXPOSE 5000

# Run the application using the entrypoint script
ENTRYPOINT ["./entrypoint.sh"]
